/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Precache static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

/**
 * Open or upgrade Dexie/IndexedDB database in service worker
 */
function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open('GhotkaliDB', 1);

    request.onupgradeneeded = () => {
      const db = request.result;
      if (!db.objectStoreNames.contains('people')) {
        const pStore = db.createObjectStore('people', { keyPath: 'id' });
        pStore.createIndex('code', 'code', { unique: true });
        pStore.createIndex('status', 'status');
        pStore.createIndex('sourceId', 'sourceId');
        pStore.createIndex('deletedAt', 'deletedAt');
        pStore.createIndex('updatedAt', 'updatedAt');
      }
      if (!db.objectStoreNames.contains('partners')) {
        const partStore = db.createObjectStore('partners', { keyPath: 'id' });
        partStore.createIndex('deletedAt', 'deletedAt');
        partStore.createIndex('createdAt', 'createdAt');
      }
      if (!db.objectStoreNames.contains('inbox')) {
        const inStore = db.createObjectStore('inbox', { keyPath: 'id' });
        inStore.createIndex('status', 'status');
        inStore.createIndex('discardedAt', 'discardedAt');
        inStore.createIndex('receivedAt', 'receivedAt');
      }
      if (!db.objectStoreNames.contains('sendLogs')) {
        const sStore = db.createObjectStore('sendLogs', { keyPath: 'id' });
        sStore.createIndex('personId', 'personId');
        sStore.createIndex('at', 'at');
        sStore.createIndex('response', 'response');
      }
      if (!db.objectStoreNames.contains('meta')) {
        db.createObjectStore('meta', { keyPath: 'key' });
      }
    };

    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

/**
 * Generates thumbnail Blob in worker if OffscreenCanvas is available
 */
async function generateWorkerThumb(blob: Blob): Promise<Blob | undefined> {
  if (typeof OffscreenCanvas === 'undefined' || typeof createImageBitmap === 'undefined') {
    return undefined;
  }
  try {
    const bitmap = await createImageBitmap(blob);
    const maxDim = 320;
    let width = bitmap.width;
    let height = bitmap.height;

    if (width > height) {
      if (width > maxDim) {
        height = Math.round((height * maxDim) / width);
        width = maxDim;
      }
    } else {
      if (height > maxDim) {
        width = Math.round((width * maxDim) / height);
        height = maxDim;
      }
    }

    const canvas = new OffscreenCanvas(Math.max(1, width), Math.max(1, height));
    const ctx = canvas.getContext('2d');
    if (!ctx) return undefined;
    ctx.drawImage(bitmap, 0, 0, width, height);
    return await canvas.convertToBlob({ type: 'image/jpeg', quality: 0.8 });
  } catch {
    return undefined;
  }
}

function getKind(mime: string): 'image' | 'pdf' | 'doc' | 'audio' | 'text' {
  if (mime.startsWith('image/')) return 'image';
  if (mime === 'application/pdf') return 'pdf';
  if (mime.startsWith('audio/')) return 'audio';
  if (mime.startsWith('text/')) return 'text';
  return 'doc';
}

/**
 * Intercept POST to share path matched via new URL('share', self.registration.scope).
 */
self.addEventListener('fetch', (event: FetchEvent) => {
  const url = new URL(event.request.url);
  const shareUrl = new URL('share', self.registration.scope);

  // Match the share path via new URL('share', self.registration.scope)
  if (
    event.request.method === 'POST' &&
    (url.pathname === shareUrl.pathname || url.pathname === `${shareUrl.pathname}/`)
  ) {
    event.respondWith(
      (async () => {
        try {
          const formData = await event.request.formData();
          const title = (formData.get('title') as string) || '';
          const text = (formData.get('text') as string) || '';
          const combinedText = [title, text].filter(Boolean).join('\n').trim();

          const mediaEntries = formData.getAll('media');
          const files: any[] = [];

          for (const entry of mediaEntries) {
            if (entry instanceof Blob) {
              const fileBlob = entry as Blob;
              const name = (entry as File).name || 'shared_file';
              const mime = fileBlob.type || 'application/octet-stream';
              const isImage = mime.startsWith('image/');
              const thumb = isImage ? await generateWorkerThumb(fileBlob) : undefined;

              files.push({
                id: crypto.randomUUID(),
                kind: getKind(mime),
                name,
                mime,
                blob: fileBlob,
                thumb,
                createdAt: Date.now(),
              });
            }
          }

          // Write one InboxItem to IndexedDB
          const db = await openDB();
          const tx = db.transaction('inbox', 'readwrite');
          const store = tx.objectStore('inbox');

          const inboxItem = {
            id: crypto.randomUUID(),
            files,
            text: combinedText,
            via: 'share',
            status: 'new',
            receivedAt: Date.now(),
          };

          await new Promise<void>((resolve, reject) => {
            const addReq = store.add(inboxItem);
            addReq.onsuccess = () => resolve();
            addReq.onerror = () => reject(addReq.error);
          });

          // Respond with 303 redirect to inbox tab with shared query param
          // Note: using resolved URL relative to the request so base path is preserved
          const redirectUrl = new URL('./?tab=inbox&shared=1', event.request.url).href;
          return Response.redirect(redirectUrl, 303);
        } catch (err) {
          // Fallback redirect on error
          const fallbackUrl = new URL('./?tab=inbox&error=share_failed', event.request.url).href;
          return Response.redirect(fallbackUrl, 303);
        }
      })()
    );
  }
});
