/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Precache static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Share target handler will be fully connected in the share-target step
self.addEventListener('fetch', (event: FetchEvent) => {
  const url = new URL(event.request.url);
  if (event.request.method === 'POST' && url.pathname.endsWith('/share')) {
    // Handled in Share Target feature
  }
});
